AIPAssignment3/src/java/au/edu/uts/aip/shopping/bean/ShoppingItem.java
package au.edu.uts.aip.shopping.bean;

import java.io.*;
import java.text.*;
import javax.enterprise.context.*;
import javax.inject.*;

@Named
@RequestScoped
public class ShoppingItem implements Serializable {
	
	private String item;
	private String description;
	private int price;
	private int quantity;
	
	
	// Default constructor.
	public ShoppingItem() {
		super();
	}
	
	
	// Constructor with parameters for easier initialisation.
	public ShoppingItem(String item, String description, int price, int quantity) {
		this.item = item;
		this.description = description;
		this.price = price;
		this.quantity = quantity;
	}
	
	
	// Returns the total price of the shopping item by multiplying the price by the
	// requested quantity.
	public double getTotalPrice() {
		return (double) price * quantity;
	}
	
	
	// Returns the item's price in a formatted string type with decimals and a
	// dollar sign.
	public String getFormattedPrice() {
		
		// Convert the price integer into a double.
		double priceDouble = (double) price / 100;
		
		// Initialise the number formatter.
		NumberFormat formatter = NumberFormat.getCurrencyInstance();
		
		// Return the formatted currency.
		return formatter.format(priceDouble);
		
	}
	
	
	// Returns the item's price multiplied by the quantity in a formatted string type
	// with decimals and a dollar sign.
	public String getFormattedTotalPrice() {
		
		// Convert the price integer into a double.
		double totalPriceDouble = getTotalPrice() / 100;
		
		// Initialise the number formatter.
		NumberFormat formatter = NumberFormat.getCurrencyInstance();
		
		// Return the formatted currency.
		return formatter.format(totalPriceDouble);
		
	}
	
	
	public String getItem() {
		return item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getPrice() {
		return price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
}

AIPAssignment3/src/java/au/edu/uts/aip/shopping/controller/HomeController.java
package au.edu.uts.aip.shopping.controller;

import java.io.*;
import javax.enterprise.context.*;
import javax.inject.*;

@Named
@SessionScoped
public class HomeController implements Serializable {
	
	// Obtain the existing ShoppingListController.
	@Inject
	private ShoppingListController shoppingListController;
	
	public String navigateJSP() {
		
		// Kill the current session.
		SessionController.killSession();
		
		//
		return "jsp/home.jsp?faces-redirect=true";
		
	}
	
	public String navigateJSF() {
		
		// Kill the current session.
		return shoppingListController.removeAll();
		
	}

	
}

AIPAssignment3/src/java/au/edu/uts/aip/shopping/controller/SessionController.java
package au.edu.uts.aip.shopping.controller;

import java.io.*;
import javax.enterprise.context.*;
import javax.faces.context.*;
import javax.inject.*;
import javax.servlet.http.*;

@Named
@RequestScoped
public class SessionController implements Serializable {
	
	// Initialise the static user session variable
	static HttpSession userSession;
	
	// Kill the current session if it exists.
	public static void killSession() {

		// Store the existing session into the userSession variable.
		userSession = getSession();
		
		
		// If session is not null, kill the session.
		if (userSession != null) {
			userSession.invalidate();
		}
		
	}
	
	
	// Returns the current session.
	public static HttpSession getSession() {
		
		// Get the current request from the Faces Context.
		FacesContext context = FacesContext.getCurrentInstance();
        HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
		
		
		// Store the current session in the class' session variable.
		return request.getSession();
		
	}
	
	
}

AIPAssignment3/src/java/au/edu/uts/aip/shopping/controller/ShoppingItemController.java
package au.edu.uts.aip.shopping.controller;

import au.edu.uts.aip.shopping.bean.ShoppingItem;
import java.io.*;
import javax.enterprise.context.*;
import javax.inject.*;
import javax.validation.constraints.*;

@Named
@RequestScoped
public class ShoppingItemController implements Serializable {
	
	private String item;
	private String description;
	private double price;
	private int quantity;
	
	// Obtain the existing ShoppingListController.
	@Inject
	private ShoppingListController shoppingListController;
	
	
	// Add an item to the ShoppingListController.
	public String add() {
		
		// Build a new shopping item based on the passed data.
		ShoppingItem shoppingItem = new ShoppingItem(item, description, (int) (price * 100), quantity);
		
		
		// Add the built item to the ShoppingListController.
		shoppingListController.add(shoppingItem);
		
		
		// Redirect to the JSF homepage.
		return "home?faces-redirect=true";
		
	}
	
	@Size(min = 1)
	public String getItem() {
		return item;
	}

	public void setItem(String item) {
		this.item = item;
	}

	@Size(min = 1)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Min(1)
	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Min(1)
	public int getQuantity() {
		return quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	
}

AIPAssignment3/src/java/au/edu/uts/aip/shopping/controller/ShoppingListController.java
package au.edu.uts.aip.shopping.controller;

import au.edu.uts.aip.shopping.bean.*;
import java.io.*;
import java.util.*;
import javax.ejb.*;
import javax.enterprise.context.*;
import javax.inject.*;

@Named
@Stateless
public class ShoppingListController implements Serializable {
	
	ArrayList<ShoppingItem> items = new ArrayList<ShoppingItem>();
	private boolean showForm = false;
	
	// Add a shopping item to the list.
	public void add(ShoppingItem shoppingItem) {
		items.add(shoppingItem);
	}
	
	
	// Setter method which allows for the user to use example items if requested.
	public void setExampleItems() {
		
		// Set the class's items to example items.
		this.items = getExampleItems();
		
	}

	
	// Automatically generates example items for use in demonstration.
	public ArrayList<ShoppingItem> getExampleItems() {
		
		// Initialise the temporary shopping list.
		ArrayList<ShoppingItem> exampleItems = new ArrayList<ShoppingItem>();
		
		
		// Create a series of example items.
		ShoppingItem exampleItem1 = new ShoppingItem("Apple", "Fuji Apples", 250, 5);
		ShoppingItem exampleItem2 = new ShoppingItem("Banana", "Wax Tipped Bananas", 120, 5);
		ShoppingItem exampleItem3 = new ShoppingItem("Milk", "Lite Milk 2L", 200, 2);
		ShoppingItem exampleItem4 = new ShoppingItem("Yoghurt", "Yoplait Vanilla", 560, 3);
		ShoppingItem exampleItem5 = new ShoppingItem("Bread", "Multigrain Sandwich", 320, 1);
		
		
		// Add the example items to the temporary list.
		exampleItems.add(exampleItem1);
		exampleItems.add(exampleItem2);
		exampleItems.add(exampleItem3);
		exampleItems.add(exampleItem4);
		exampleItems.add(exampleItem5);
		
		
		// Return the built example list.
		return exampleItems;
		
	}
	
	
	// Removes all items from the items list.
	public String removeAll() {
		
		// Remove all items from the shopping list.
		items.removeAll(items);
		
		
		// Kill the current session.
		SessionController.killSession();
		
		
		// Redirect to JSF homepage.
		return "/jsf/home.xhtml?faces-redirect=true";
		
	}
	
	
	// Returns the relevant form text depending whether the form is being
	// shown or not.
	public String getFormText() {
		return showForm ? "Close form..." : "Add item to the list...";
	}
	
	
	// Show the add form if it is hidden, and vice versa.
	public void invertShowForm() {
		showForm = !showForm;
	}
	
	
	// Returns whehter or not the list contains items.
	public boolean getHasItems() {
		return !items.isEmpty();
	}
	
	
	public ArrayList<ShoppingItem> getItems() {
		return items;
	}
	
	public void setItems(ArrayList<ShoppingItem> items) {
		this.items = items;
	}

	public boolean isShowForm() {
		return showForm;
	}

	public void setShowForm(boolean showForm) {
		this.showForm = showForm;
	}
	
}

AIPAssignment3/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<ui:insert name="head" >
        <ui:include src="jsf/head.xhtml" />
    </ui:insert>
    <h:body>
		<h:link value="Home" outcome="/index" />
		<h1>Shopping List</h1>

		<h:panelGroup>
			<h2>How would you like to navigate the system today?</h2>
		</h:panelGroup>
		
		<h:form>
			<h:panelGrid styleClass="displayTable" columns="2">

				<h:panelGroup>
					<h3><h:commandLink action="#{homeController.navigateJSP}" value="JavaServer Pages" /></h3>
					<p>Handwritten inline Java code within JSP files. Stateless. Non-modular.</p>
				</h:panelGroup>

				<h:panelGroup>
					<h3><h:commandLink action="#{homeController.navigateJSF}" value="JavaServer Faces" /></h3>
					<p>Stateful server-generated UI via JSF Framework. EJB. AJAX. Full MVC pattern.</p>
				</h:panelGroup>

			</h:panelGrid>
		</h:form>
		<br/><br/>
		<p>Please note that selecting either of these options will invalidate any existing sessions.</p>
		
    </h:body>
</html>

AIPAssignment3/web/jsf/add.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core">
	<ui:composition>
		<h:form>
			<table class="form">
				<tr>
					<td><h:outputText value="Item" /></td>
					<td><h:inputText id="item" value="#{shoppingItemController.item}" required="true"
									 requiredMessage=" Please enter an item." autocomplete="off" />
						<h:message id="itemMessage" for="item"></h:message>
					</td>
				</tr>
				<tr>
					<td><h:outputText value="Description" /></td>
					<td><h:inputText id="description" value="#{shoppingItemController.description}" required="true"
									 requiredMessage=" Please enter a description." autocomplete="off" />
						<h:message id="descriptionMessage" for="description"></h:message>
					</td>
				</tr>
				<tr>
					<td><h:outputText value="Price" /></td>
					<td><h:inputText id="price" value="#{shoppingItemController.price}" required="true"
									 requiredMessage=" Please enter the item's price." autocomplete="off"
									 validatorMessage=" Please enter a valid price greater than 0." />
						<h:message id="priceMessage" for="price"></h:message>
					</td>
				</tr>
				<tr>
					<td><h:outputText value="Quantity" /></td>
					<td><h:inputText id="quantity" value="#{shoppingItemController.quantity}" required="true"
									 requiredMessage=" Please enter the item's price." autocomplete="off"
									 validatorMessage=" Please enter a valid quantity greater than 0." />
						<h:message id="quantityMessage" for="quantity"></h:message>
					</td>
				</tr>
				<tr>
					<td></td>
					<td><h:commandButton id="submit" 
										 action="#{shoppingItemController.add}" 
										 value="Submit">
							<f:ajax execute="@form" render="listItems itemMessage descriptionMessage priceMessage quantityMessage" />
						</h:commandButton>
					</td>
				</tr>
			</table>
		</h:form>
	</ui:composition>
</html>

AIPAssignment3/web/jsf/head.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	<ui:composition>
		<h:head>
			<title>Shopping List</title>
			<!--<h:outputStylesheet library="css" name="style.css" />-->
			<link rel="stylesheet" type="text/css" href="/AIPAssignment3/resources/style.css" />
		</h:head>
	</ui:composition>
</html>


AIPAssignment3/web/jsf/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	  xmlns:f="http://xmlns.jcp.org/jsf/core">
	<ui:insert name="head" >
		<ui:include src="head.xhtml" />
	</ui:insert>
	
	<h:body>
		<ui:insert name="pageheader" >
			<ui:include src="pageheader.xhtml" />
		</ui:insert>
    </h:body>
	
	<h2>Producing the shopping list using JavaServer Faces.</h2>
	<p><h:outputText value="There are currently no items in the shopping list." rendered="#{not shoppingListController.hasItems}" /></p>
	
	<h:dataTable id="listItems" var="item" value="#{shoppingListController.items}" rendered="#{shoppingListController.hasItems}">
		<h:column>
			<f:facet name="header">Item</f:facet>
			<h:outputText value="#{item.item}"/>
		</h:column>
		<h:column>
			<f:facet name="header">Description</f:facet>
			<h:outputText value="#{item.description}"/>
		</h:column>
		<h:column>
			<f:facet name="header">Price</f:facet>
			<h:outputText value="#{item.formattedPrice}"/>
		</h:column>
		<h:column>
			<f:facet name="header">Quantity</f:facet>
			<h:outputText value="#{item.description}"/>
		</h:column>
		<h:column>
			<f:facet name="header">Total Price</f:facet>
			<h:outputText value="#{item.formattedTotalPrice}"/>
		</h:column>
	</h:dataTable><br/>
	
	<h:form>
		<p><h:commandLink value="Generate example items" action="#{shoppingListController.setExampleItems}" rendered="#{not shoppingListController.hasItems}" /></p><br/>
		<p><h:commandLink value="#{shoppingListController.formText}" action="#{shoppingListController.invertShowForm}" /></p><br/>
	</h:form>
	
	<h:panelGroup rendered="#{shoppingListController.showForm}">
		<ui:insert name="add">
			<ui:include src="add.xhtml" />
		</ui:insert>
	</h:panelGroup>

</html>

AIPAssignment3/web/jsf/pageheader.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
	  xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <ui:composition>
		<h:form>
			<h:panelGroup>
				<h:link value="Home" outcome="/index" /> - <h:link value="JSF Home" outcome="/jsf/home" /> - <h:commandLink action="#{shoppingListController.removeAll}" value="Destroy Session" />
				<h1>Shopping List</h1>
			</h:panelGroup>
		</h:form>
	</ui:composition>
</html>

AIPAssignment3/web/jsp/add.jsp
<%@page import="java.util.*"%>
<%@page import="au.edu.uts.aip.shopping.bean.*"%>
<%@page import="au.edu.uts.aip.shopping.controller.*"%>
<jsp:useBean id="shoppingListController" class="au.edu.uts.aip.shopping.controller.ShoppingListController" scope="session" />
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
		<%@include file="head.html" %>
    </head>
    <body>
		<%@include file="pageheader.html" %>
		<h2>Add an item to the shopping list using JSP.</h2>
		<br>
		<form action="additem.jsp" method="POST">
			<table class="form">
				<tr>
					<td>Item</td>
					<td><input name="item" type="text" required /></td>
				</tr>
				<tr>
					<td>Description</td>
					<td><input name="description" type="text" required /></td>
				</tr>
				<tr>
					<td>Price</td>
					<td><input name="price" type="number" min="1" step="0.01" required /></td>
				</tr>
				<tr>
					<td>Quantity</td>
					<td><input name="quantity" type="number" min="1" required /></td>
				</tr>
				<tr>
					<td></td>
					<td><input name="item" type="submit" /></td>
				</tr>
			</table>
		</form>
	</body>
</html>

AIPAssignment3/web/jsp/additem.jsp
<%@page import="au.edu.uts.aip.shopping.bean.*"%>
<jsp:useBean id="shoppingListController" class="au.edu.uts.aip.shopping.controller.ShoppingListController" scope="session" />
<%
	
	try {
	
		// Receive item details from POST parameters.
		String name = request.getParameter("item");
		String description = request.getParameter("description");
		int price =  (int) (Double.parseDouble(request.getParameter("price")) * 100);
		int quantity = Integer.parseInt(request.getParameter("quantity"));

		
		// Build a new shopping item to add to the list.
		ShoppingItem shoppingItem = new ShoppingItem(name, description, price, quantity);

		
		// Add the new shopping item to the list.
		shoppingListController.add(shoppingItem);

		
		// Redirect to the homepage.
		String redirectURL = "/AIPAssignment3/faces/jsp/home.jsp";
		response.sendRedirect(redirectURL);
	
	} catch (NullPointerException e) {
		
		// Alert the user that not all parameters were provided.
		out.print("Not all parameters provided.");
		
	}
	
%>

AIPAssignment3/web/jsp/destroy.jsp
<%@page import="au.edu.uts.aip.shopping.controller.SessionController"%>
<%

	// Kills the existing session.
	SessionController.killSession();
	
	// Redirect to the homepage.
	String redirectURL = "/AIPAssignment3/faces/jsp/home.jsp";
    response.sendRedirect(redirectURL);
	
%>

AIPAssignment3/web/jsp/generate.jsp
<jsp:useBean id="shoppingListController" class="au.edu.uts.aip.shopping.controller.ShoppingListController" scope="session" />
<%

	// Add example items to the Shopping List Controller.
	shoppingListController.setExampleItems();
	
	// Redirect to the homepage.
	String redirectURL = "/AIPAssignment3/faces/jsp/home.jsp";
    response.sendRedirect(redirectURL);
	
%>

AIPAssignment3/web/jsp/home.jsp
<%@page import="java.util.*"%>
<%@page import="au.edu.uts.aip.shopping.bean.*"%>
<%@page import="au.edu.uts.aip.shopping.controller.*"%>
<jsp:useBean id="shoppingListController" class="au.edu.uts.aip.shopping.controller.ShoppingListController" scope="session" />
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
		<%@include file="head.html" %>
    </head>
    <body>
		<%@include file="pageheader.html" %>
		<h2>Producing the shopping list using JavaServer Pages.</h2>
		<%			
			
			// Check whether the shopping list contains items.
			if (shoppingListController.getHasItems()) {

		%>		
		<table class="shoppingListTable">
			<thead>
			<th>Item</th>
			<th>Description</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Total Price</th>
		</thead>
		<tbody>
			<%
				
				// Output each item within the shopping list, with a foreach loop
				// generating each row and each cell manually using their
				// corresponding HTML tags.
				for (ShoppingItem shoppingItem : shoppingListController.getItems()) {

					out.print("<tr>");

					out.print("<td>");
					out.print(shoppingItem.getItem());
					out.print("</td>");

					out.print("<td>");
					out.print(shoppingItem.getDescription());
					out.print("</td>");

					out.print("<td>");
					out.print(shoppingItem.getFormattedPrice());
					out.print("</td>");

					out.print("<td>");
					out.print(shoppingItem.getQuantity());
					out.print("</td>");

					out.print("<td>");
					out.print(shoppingItem.getFormattedTotalPrice());
					out.print("</td>");

					out.print("</tr>");

				}

				%>
		</tbody>
	</table>
		<br>
		<p><a href="add.jsp">Add item to the list</a></p>
			<%

			} else {

			%>
			<p>There are currently no items in the shopping list.</p><br>
			<p><a href="add.jsp">Add item to the list</a></p>
			<p><a href="generate.jsp">Generate example items</a></p>
			<%
			}
			%>
	</body>
</html>